name: Android CI

on: [push]

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  assemble_ui_test_artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build APK for UI test after Unit tests
        run: |
          ./gradlew test
          ./gradlew assembleDebug
          ./gradlew assembleDebugAndroidTest

      - name: Upload app-debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

        - name: Upload app-debug-androidTest APK
          uses: actions/upload-artifact@v2
          with:
            name: app-debug-androidTest
            path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#       - name: Install NDK
#         run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
#       - name: Make gradlew executable
#         run: chmod +x ./gradlew
#       - name: Build with Gradle
#         run: ./gradlew assembleDebug

#     Берем файл keystore из специального отдельного репозитория и кладем его в папку app/keystore
      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: app/keystore
#     Собираем релизные и подписаные apk-файлы для CQ и Dashly
      - name: Build signed APK
        run: |
          ./gradlew test
          ./gradlew assembleRelease
          ./gradlew bundleRelease
#     Выливаем apk-файл для CQ
      - name: Upload CQ APK
        uses: actions/upload-artifact@v2
        with:
          name: app-common-release.apk
          path: app/build/outputs/apk/common/release/app-common-release.apk
#     Выливаем apk-файл для Dashly
      - name: Upload Dashly APK
        uses: actions/upload-artifact@v2
        with:
            name: app-us-release.apk
            path: app/build/outputs/apk/us/release/app-us-release.apk
